### PR TITLE
更新贡献说明

### PR DESCRIPTION
**Pull request by pythonton**
大锅，难道这句是直译过来的嘛~

- 优化项
    - 更新贡献说明，有句话明显是直译过来的...

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/bk-sops?pullRequest=780) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-sops?pullRequest=780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-sops?pullRequest=780) it.</sub>

**Comment by pagezhou** [comment]
感谢提出文档优化方案，请修改PR，将目标分支改为V3.3.X，不要直接合入master

**Comment by pythonton** [comment]
> 感谢提出文档优化方案，请修改PR，将目标分支改为V3.3.X，不要直接合入master

好滴。

大锅，首页也没提示，让我合入**V3.3.X**啊~

**Comment by pagezhou** [comment]
建议列个Issue，后续我们在wiki-参与社区文档中加入开发者注意事项

**Pull request merged**
